---
title: "Visualizing SOE Indicators"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: lumen
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(heatmaply)
library(corrplot)
library(htmlwidgets)
library(here)
library(tseries)
library(stringr)
library(dplyr)

source("load_data.R")
```

Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput("Var",
            label = "Variable",
            choices = var_ids,
            selected = var_ids[1],
            selectize = TRUE,
            multiple = TRUE)
selectizeInput("EPU",
                     label = "EPU",
                     choices = epu_ids,
                     selected = epu_ids[1],
                     multiple = TRUE)




```


Row {data-height=750}
-------------------------------------

### Normalized Indicator Series

```{r}
out <- reactive({
      
      # if (input$EPU %in% "all"){
        soe %>%
        dplyr::filter(Var %in% input$Var) %>% 
        {if (!input$EPU %in% 'all')
          dplyr::filter(., EPU %in% input$EPU) else .} %>% 
        group_by(Var, EPU) %>%
        mutate(count = n()) %>%
        ungroup() %>%
        filter(count >= 10,
               !str_detect(Var,"reference"),
               !is.na(Value)) %>%
        tidyr::unite(., Var, Var = c("Var","EPU"), sep = " ")

    })
    
renderPlotly({
      p <- ggplot(data = out()) +
        geom_line(aes(x = Time, y = Value, group = Var, color = Var)) +
        ylab("Normalized Value") +
        guides(color = FALSE)
      ggplotly(p) %>% 
        layout(autosize = T)
    })

```

Row {data-height=350}
-------------------------------------
   
### Data Input


```{r}

```
    
